### ISSUE TITLE
Spelling error in configure.ac

### ISSUE THREAD

**Issue by ghost** [depressed-pho/bedrock-ui-tweaks#1]
In line 9 of configure.ac the project link is misspelled:
```
    [https://github.com/depressed-pho/bedrock-ui-twekas])
```
(I don't know what autoconf is or does so I have no idea what the effect of this is.)
(This is Auldrick by the way.)

**Comment by depressed-pho** [comment]
Thanks. The URL is however not used at all in this project, so the misspelled URL had in fact no effects :D
